services:
  express:
    image: ottosfelix/express_app:latest
    ports:
      - 8080:8080
    container_name: express_app
    
  watchtower:
    image: containrrr/watchtower:1.7.1
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
      - DOCKER_API_VERSION=1.40
      - REPO_USER=${DOCKER_USER}
      - REPO_PASS=${DOCKER_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower